### ISSUE TITLE
The first hook on ApplyRecursiveSearch wasn't found (and a failure to unload properly)

### ISSUE THREAD

**Issue by justastranger** [Ishigh1/RecursiveCraft#11]
```
[19:56:51] [.NET ThreadPool Worker/INFO] [tML]: Initializing: RecursiveCraft v2.0.0.1
[19:56:51] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Recipe::FindRecipes(bool) modified by RecursiveCraft
[19:56:51] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.Exception: The first hook on ApplyRecursiveSearch wasn't found
   at RecursiveCraft.RecursiveCraft.ApplyRecursiveSearch(ILContext il) in RecursiveCraft.cs:line 209
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Recipe.add_FindRecipes(Manipulator )
   at RecursiveCraft.RecursiveCraft.Load() in RecursiveCraft.cs:line 29
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 303
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 114
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[19:56:51] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading RecursiveCraft
The mod(s) have been automatically disabled.
System.Exception: The first hook on ApplyRecursiveSearch wasn't found
   at RecursiveCraft.RecursiveCraft.ApplyRecursiveSearch(ILContext il) in C:\Users\Ishigh\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\RecursiveCraft\RecursiveCraft.cs:line 209
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Recipe.add_FindRecipes(Manipulator )
   at RecursiveCraft.RecursiveCraft.Load() in C:\Users\Ishigh\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\RecursiveCraft\RecursiveCraft.cs:line 29
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 306
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
[19:56:51] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: RecursiveCraft
```

```
[19:57:14] [.NET ThreadPool Worker/INFO] [tML]: Unloading: Recursive Craft
[19:57:14] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Recipe::FindRecipes(bool) unmodified by RecursiveCraft
[19:57:14] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Remove(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Unmodify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Unmodify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Unmodify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Recipe.remove_FindRecipes(Manipulator )
   at RecursiveCraft.RecursiveCraft.Unload() in RecursiveCraft.cs:line 51
   at Terraria.ModLoader.Mod.UnloadContent() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 35
   at Terraria.ModLoader.ModContent.UnloadModContent() in tModLoader\Terraria\ModLoader\ModContent.cs:line 423
   at Terraria.ModLoader.ModLoader.Mods_Unload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 232
   at Terraria.ModLoader.ModLoader.Unload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 203
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 123
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 114
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[19:57:14] [.NET ThreadPool Worker/FATAL] [tML]: One or more errors occured while unloading and tModLoader must be restarted to prevent further issues.
RecursiveCraft was unable to unload properly. Modders must use defensive programming to ensure unloading completes regardless of any errors during loading.
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Remove(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Unmodify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Unmodify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Unmodify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Recipe.remove_FindRecipes(Manipulator )
   at RecursiveCraft.RecursiveCraft.Unload() in C:\Users\Ishigh\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\RecursiveCraft\RecursiveCraft.cs:line 51
   at Terraria.ModLoader.Mod.UnloadContent() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 35
   at Terraria.ModLoader.ModContent.UnloadModContent() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 423
   at Terraria.ModLoader.ModLoader.Mods_Unload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 232
   at Terraria.ModLoader.ModLoader.Unload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 203
```

tModLoader version is `1.4.3.2+0.12-1.4-Alpha-3192afa8df3670f9af0324da58a932de73be2b21-5249441319801399378`.

Full log can be found [here](https://pastebin.com/2j1W7pF8)

**Comment by Ishigh1** [comment]
Now fixed, sorry I didn't see there was a new issue earlier
