### ISSUE TITLE
[1.4-preview] Crashes client when loading.

### ISSUE THREAD

**Issue by WhitePhant0m** [Ishigh1/RecursiveCraft#12]
RecursiveCraft crashes my client when trying to load it on the 1.4-preview branch.

```
[01:33:33] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at RecursiveCraft.RecursiveCraft.UpdateInventoryState() in RecursiveCraft.cs:line 151
   at RecursiveCraft.RecursiveCraft.ApplyKey(orig_Update orig, Main self, GameTime gameTime) in RecursiveCraft.cs:line 158
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 543
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at System.Threading.Thread.StartCallback()
```
```
[01:33:33] [Main Thread/FATAL] [Terraria]: Main engine crash
System.NullReferenceException: Object reference not set to an instance of an object.
   at RecursiveCraft.RecursiveCraft.UpdateInventoryState() in RecursiveCraft.cs:line 151
   at RecursiveCraft.RecursiveCraft.ApplyKey(orig_Update orig, Main self, GameTime gameTime) in RecursiveCraft.cs:line 158
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 543
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
   ```
[client.log](https://github.com/Ishigh1/RecursiveCraft/files/8790008/client.log)

I also tried re-building it myself on preview and that didn't help either.

**Comment by Ishigh1** [comment]
You have a lot of mods enabled, and with this mod alone I am not affected by this issue
Can you try to reduce the number of mods enabled ? seems like some of the mods like Magic Storage aren't working anymore on preview

**Comment by WhitePhant0m** [comment]
Hmm... I tried disabling some of the other mods, and the issue went away, but the interesting part is that I can no longer recreate the crash with the same mod list...

**Comment by Ishigh1** [comment]
It may be a race condition ?
Well if that's the case I can push a fix
