### ISSUE TITLE
Game freeze when trying to see a craft in recipe browser

### ISSUE THREAD

**Issue by leoperes2** [Ishigh1/RecursiveCraft#8]
after i installed the recursivecraft when i put an item in the recipe browser and click to see a craft, the game freeze and i have to alt+f4 to close. But only if i put an item in it, without the item it works normally. I tried changing the config from -1 to 1 but keeps crashing.

**Comment by leoperes2** [comment]
[20:46:58] [1/ERROR] [Terraria]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RecipeBrowser.RecipeCatalogueUI.SetRecipe(Int32 index) in RecipeBrowser\RecipeCatalogueUI.cs:line 747
   at RecipeBrowser.UIElements.UIRecipeSlot.Click(UIMouseEvent evt) in RecipeBrowser\UIElements\UIRecipeSlot.cs:line 67
   at Terraria.UI.UserInterface.Update(GameTime time)
   at Terraria.ModLoader.ModHooks.UpdateUI(GameTime gameTime)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main , GameTime )

the error from tmodloader 64bits

**Comment by Ishigh1** [comment]
Yeah, this error is known, it's from Recipe Browser side, there was a pull request to solve this but I can't do anything

**Comment by Ishigh1** [comment]
To solve this bug you could build and use this fork of Recipe Browser
https://github.com/ExterminatorX99/RecipeBrowser
